export enum UserError {
  ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INACTIVE = 'USER_INACTIVE',
  NOT_FOUND = 'USER_NOT_FOUND',
  SELF_UPDATE_FORBIDDEN = 'USER_SELF_UPDATE_FORBIDDEN',
  SELF_DELETE_FORBIDDEN = 'USER_SELF_DELETE_FORBIDDEN',
}
